highlighter: rouge
title: Do You Need a Stent?
url: http://www.doineedastent.com
description: Site to help empower patients who have been suggested to have a stent
author:
  twitter: geoffreyrosen
google_site_verification: UA-92774366-1
gems:
  - jekyll-seo-tag