highlighter: rouge
title: Do You Need a Stent?
url: http://www.doineedastent.com
description: Site to help empower patients who have been suggested to have a stent
author:
  twitter: geoffreyrosen
gems:
  - jekyll-seo-tag